import { Venue, BoothReservation } from "@/types";

export const MOCK_VENUES: Venue[] = [
  {
    id: "venue-lawrenceville",
    name: "Adult World - Lawrenceville",
    address: "US-15 & PA-49, Lawrenceville, PA 16929",
    latitude: 41.9984,
    longitude: -77.1262,
    boothCount: 12,
    activeReservationsCount: 4,
  },
  {
    id: "venue-paintedpost",
    name: "Adult World - Painted Post",
    address: "Addison Rd, Painted Post, NY 14870",
    latitude: 42.1623,
    longitude: -77.0984,
    boothCount: 16,
    activeReservationsCount: 6,
  },
  {
    id: "venue-elmira",
    name: "Adult World - Elmira",
    address: "Lake Rd, Horseheads/Elmira, NY 14903",
    latitude: 42.1485,
    longitude: -76.8123,
    boothCount: 10,
    activeReservationsCount: 2,
  },
  {
    id: "venue-binghamton",
    name: "Adult World - Binghamton",
    address: "Front St, Binghamton, NY 13905",
    latitude: 42.1321,
    longitude: -75.9123,
    boothCount: 14,
    activeReservationsCount: 5,
  },
];

export const MOCK_RESERVATIONS: BoothReservation[] = [
  {
    id: "res-1",
    userId: "user-101",
    userHandle: "NeonKnight99",
    venueId: "venue-lawrenceville",
    venueName: "Adult World - Lawrenceville",
    boothNumber: 4,
    startTime: new Date(Date.now() - 15 * 60000).toISOString(),
    endTime: new Date(Date.now() + 45 * 60000).toISOString(),
    status: "GREEN_LIGHT",
    preference: "HANGOUT",
    note: "Looking to chill and watch sci-fi/fantasy videos together in Booth #4.",
  },
  {
    id: "res-2",
    userId: "user-102",
    userHandle: "MidnightRider",
    venueId: "venue-lawrenceville",
    venueName: "Adult World - Lawrenceville",
    boothNumber: 2,
    startTime: new Date(Date.now() - 30 * 60000).toISOString(),
    endTime: new Date(Date.now() + 30 * 60000).toISOString(),
    status: "GREEN_LIGHT",
    preference: "GIVE_OR_RECEIVE",
    note: "Arrived at 10 AM, open to give or receive.",
  },
  {
    id: "res-3",
    userId: "user-103",
    userHandle: "ShadowWalker",
    venueId: "venue-paintedpost",
    venueName: "Adult World - Painted Post",
    boothNumber: 7,
    startTime: new Date(Date.now() + 15 * 60000).toISOString(),
    endTime: new Date(Date.now() + 75 * 60000).toISOString(),
    status: "YELLOW_LIGHT",
    preference: "RECEIVE",
    note: "En route, arriving in ~15 mins.",
  },
  {
    id: "res-4",
    userId: "user-104",
    userHandle: "CrimsonViper",
    venueId: "venue-lawrenceville",
    venueName: "Adult World - Lawrenceville",
    boothNumber: 8,
    startTime: new Date(Date.now() - 5 * 60000).toISOString(),
    endTime: new Date(Date.now() + 25 * 60000).toISOString(),
    status: "RED_LIGHT",
    preference: "HANGOUT",
    note: "Occupied right now, check back later.",
  },
];
